### ISSUE TITLE
Library won't reconnect.

### ISSUE THREAD

**Issue by skorokithakis** [marvinroger/async-mqtt-client#18]
I have the library set to reconnect on disconnection, but that doesn't work, and I find the clients frequently disconnected even though they are on WiFi. Is there a setting I can use, or another way I can make them keep trying to reconnect?

**Comment by eos1d3** [comment]
Confirmed that the reconnection never works for me. And keepalive also never works. These ruins the library to useless. Otherwise, this library would be nice. It has everything. But these two issues kill everything. 

I reported the issues for a while. Hope there is a chance to fix them.

**Comment by skorokithakis** [comment]
Yeah, agreed. I'm thinking of either going back to the synchronous library, but I'll see if I can sidestep the issues by adding a call every 5 seconds to connect if not connected.

**Comment by eos1d3** [comment]
I tested this with Adafruit IO and also Mosquitto. I remember even I publish every 60 seconds, there will finally a disconnection which breaks the connection permanently until restart. 
 Adafruit IO keepalive is 5 mins. So every 60 seconds is good to keep connection. But what I found is:
1. Sometimes there will be a disconnection with random time period.
2. Sometimes disconnection is never detected and the the program still works as if connection is still good. But nothing is actually published.

**Comment by skorokithakis** [comment]
Ouch, the second kills it. I can deal with random disconnections if I have the script try to connect every 10-15 seconds, but if it doesn't even know it's disconnected, that's a no-go...

**Comment by NeilSpp** [comment]
I have such a case, after the connection is disconnected  permanently until restart. I publish every 60 seconds to server.

**Comment by marvinroger** [comment]
You're right, the library is not stable, that is why it is not actually released as v1. I've never had this kind of issue however. So you experience this behavior with the example sketch, for example?

We will obviously try to solve these issues, unfortunately I don't have ESPs at the moment for 2 weeks so I cannot do anything during this timelapse.

**Comment by eos1d3** [comment]
Right! Just tested with Fullfeatured example with Adafruit IO and Mosquitto on PI3. Both have Keepalive and disconnection problem. Once disconnected, there is no way to reconnect until restart.

I am using NodeMCU which is actually ESP12E. And all related software/libraries are all updated to the newest version.

This library has good potential. Don't give up!

I can help if you find something to change. You can tell me what to try if you want.

**Comment by marvinroger** [comment]
I won't give up, don't worry. :wink: 
Take a look at #1... This is weird! When I tested it, even with public brokers, it was very stable, even reconnections were stable. However I am not sure for the keep-alive.

Maybe an esp8266/Arduino or me-no-dev/ESPAsyncTCP update changed some things that we will need to figure out.

**Comment by eos1d3** [comment]
For me, with the FullFeatured example, I will have two conditions:

1. The example program will detect disconnection at random time intervals, Sometimes 60 seconds, sometimes 5 mins.Once it detected, the library will try to reconnect, but it never gets connected.  I tried to publish at a fixed internal, when it gets disconnected, the publish never reports error. It looks like connection is good. But I see nothing from the broker.

2. The example program never detects the disconnection when connection is actually broken. I even tried to wait some hours and it just cannot resume.

**Comment by skorokithakis** [comment]
You can see my usage here:

https://gitlab.com/stavros/sonoff/blob/08ac399becc01eb61666fdaa44c9daabd84d8e04/src/main.ino

**Comment by marvinroger** [comment]
Can you test https://github.com/marvinroger/async-mqtt-client/pull/19?

**Comment by kiralikbeyin** [comment]
Will be a fix very soon or i am planing to go with https://github.com/i-n-g-o/esp-mqtt-arduino

**Comment by marvinroger** [comment]
The thing is I am not able to reproduce... I've been running a sample sketch for 72 hours, publishing at different rates, and no disconnection so far. So I am kind of stuck!

**Comment by marvinroger** [comment]
When I restart my mosquitto instance, it reconnects just fine. I am pretty sure of the answer, but you're all using a modern mosquitto broker, right? I am using v1.4.9.

**Comment by skorokithakis** [comment]
I'm using 1.4.8 :/ Too bad you can't reproduce this, it happened pretty regularly for me (disconnection after a few days, without reconnection).

**Comment by eos1d3** [comment]
Right, I use everything (Arduino IDE, EPS8266 library, ESPAsyncTCP,
Mosquitto broker on PI3...) with the newest version.
And it NEVER can reconnect once.

**Comment by kiralikbeyin** [comment]
I'm using mosca, i think this is not related with broker.

maybe we all use ESPAsyncWebServer except @marvinroger

**Comment by eos1d3** [comment]
It may not be MQTT broker issue. The problem exists for both Adafruit IO and Mosquitto broker.

**Comment by skorokithakis** [comment]
I switched the exact same code from async MQTT client to the normal, synchronous MQTT client and reconnections work fine.

**Comment by marvinroger** [comment]
@kiralikbeyin said he was using ESPAsyncWebServer, are you @skorokithakis and @eos1d3? As it uses the same underlying ESPAsyncTCP, there might be a conflict or something.

**Comment by skorokithakis** [comment]
Not that I know of. This is my code: https://gitlab.com/stavros/sonoff/blob/08ac399becc01eb61666fdaa44c9daabd84d8e04/src/main.ino

**Comment by kiralikbeyin** [comment]
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <ArduinoOTA.h>
#include <FS.h>
#include <Hash.h>
#include <ESPAsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <ESP8266HTTPClient.h>
#include <ESP8266httpUpdate.h>
#include <StreamString.h>
#include <TimeLib.h>
#include <NtpClientLib.h>

#include "AsyncJson.h"
#include "ArduinoJson.h"
 #include <ESPAsyncWiFiManager.h>   

Should be a DNS problem

**Comment by eos1d3** [comment]
I use this: https://github.com/me-no-dev/ESPAsyncTCP

I did try two versions of the above in July, both have the same problem.

One thing I cannot confirm, when I tested this library for the first time (at the time you released it), I remember I see a lot of disconnection and reconnection.  Then after changes of this and that, it never works now.

**Comment by marvinroger** [comment]
Are you all using hostnames instead of direct IP?

**Comment by skorokithakis** [comment]
I'm using a hostname, yes. You think resolution is failing?

**Comment by eos1d3** [comment]
I use Mosquitto broker on PI3 at home with IP (192.168.2.xxx). It never works!

**Comment by kiralikbeyin** [comment]
mqttClient.setServer(IPAddress(172, 20, 10, 7), 1883);
BUT
MDNS.begin(config.DeviceName.c_str());

**Comment by eos1d3** [comment]
It can't be DNS problem as it can connect, public and subscribe normally for a while and then die. 
If it is DNS, it won't reach the broker.

**Comment by eos1d3** [comment]
@marvinroger What is the date of your  ESPAsyncTCP library?

**Comment by marvinroger** [comment]
@skorokithakis I don't know, I'm trying to isolate the issue
@eos1d3 the reconnection (not disconnection) issue might eventually come from DNS (it might work in the first place and not work in subsequent reconnects). I am just trying to gather the maximum amount of information to reproduce

The latest commit https://github.com/me-no-dev/ESPAsyncTCP/commit/6271c625061c8b55ce2b5c0a0f93f933d0fe8a20

On what OS is your broker running? Linux for @eos1d3, what about @kiralikbeyin and @skorokithakis ? Because I remember I had an issue with ports not being closed properly.

**Comment by skorokithakis** [comment]
Ubuntu for me, although it's working fine with a different client library, so I'm not sure if it's the broker's issue, hmm.

**Comment by eos1d3** [comment]
My Mosquitto is on PI3 Jessie (Debian Linux).
My test with Mosquitto used IP only.

**Comment by kiralikbeyin** [comment]
@marvinroger iOS with mosca.

**Comment by marvinroger** [comment]
@skorokithakis it might be since WiFiClient and ESPAsyncTCP are different on some points, notably the local port randomization. And I am on Windows! Can you try with this ESPAsyncTCP: https://github.com/me-no-dev/ESPAsyncTCP/archive/46cd942d3cc9fe84c2e606b4c4cf8ca9865356a3.zip

**Comment by eos1d3** [comment]
Installed the above ESPAsyncTCP, using FullyFeatured example, with displaying "One minute passed" every one minute in loop(). Tested with Adafruit IO, the problem is there.

You can only see "Reconnecting to MQTT..." and no ""** Connected to the broker **".

```
Connecting to Wi-Fi........ OK
Connecting to MQTT...
** Connected to the broker **
Subscribing at QoS 2, packetId: 1
Publishing at QoS 0
Publishing at QoS 1, packetId: 2
Publishing at QoS 2, packetId: 3
** Publish acknowledged **
  packetId: 2
** Subscribe acknowledged **
  packetId: 1
  qos: 2
** Publish acknowledged **
  packetId: 3
One minute passed
** Disconnected from the broker **
Reconnecting to MQTT...
One minute passed
One minute passed
One minute passed
One minute passed
One minute passed
One minute passed
One minute passed
One minute passed
```

Will test with Mosquitto too.

**Comment by eos1d3** [comment]
Mosquitto Broker on PI3
FullyFeatured example
above ESPAsyncTCP
loop changed to:

```
void loop() {
  if (millis() >= t0 + 30000) {
    Serial.println("30 seconds passed");
    t0 = millis();
    mqttClient.disconnect();
  }
}
```


Now, with more than 10 disconnections, it **CAN** always connect to broker!!

**Comment by eos1d3** [comment]
Back to Adafruit IO example above, **keep everything unchanged**.
But changed 
`mqttClient.setServer("io.adafruit.com", 1883);`
to
`mqttClient.setServer(IPAddress(52, 70, 203, 194), 1883);`

Re-connection WORKS!

**Comment by skorokithakis** [comment]
This may also have something to do with the fact that it tries to reconnect once, and, if that fails, it never tries again. It would be better if it could be set to reconnect on an interval.

**Comment by eos1d3** [comment]
When to reconnect can actually be done by your application and just do nothing in `onMqttDisconnect`.

**Comment by marvinroger** [comment]
Yes, I would like to keep the library as low-level as possible.

So the problem comes from https://github.com/me-no-dev/ESPAsyncTCP/commit/4edce1e9e538c040e029e50001cc4b496d509505 (before this commit: works on Linux/Unix only and after this commit: works on Windows only)

But @eos1d3 you're saying that DNS fails too, after subsequent reconnects?

**Comment by marvinroger** [comment]
Anyway, @me-no-dev, we had a discussion about the local port randomization on Gitter (at which point you actually committed https://github.com/me-no-dev/ESPAsyncTCP/commit/4edce1e9e538c040e029e50001cc4b496d509505), but as said above it does not work fine in Linux/Unix env when disconnected not cleanly. WiFiClient works fine with both Windows and Linux servers, maybe you can borrow the randomization from there? (I am not sure I know what I am talking about though)

**Comment by eos1d3** [comment]
Summaries for my tests:
1. When you use hostname, reconnection never works for 3 versions of ESPAsyncTCP with Adafruit IO.
2. For Adafruit IO and Mosquitto borkers, when using IP address, reconnection works for 3 versions of ESPAsyncTCP, including the latest one.
3. For all test, I use `mqttClient.disconnect()` to force a disconnection (without waiting for broker to disconnect)

So, my tests point to DNS problem. When using hostname, it can only connect once then no more for subsequent reconnects.

**Comment by me-no-dev** [comment]
@marvinroger after the mentioned commit, the port randomisation works the same exact way as in the regular WiFiClient. Must be something else ;)

**Comment by me-no-dev** [comment]
One question! Does the reconnect to dns hostname happen inside async callback?

**Comment by marvinroger** [comment]
It does! I didn't think about this...

**Comment by me-no-dev** [comment]
I know of this issue and it's on my to-do list to get it to work. Please file it on my repo so I can have it nagging me :) In a mean time, you can cache the IP of the broker (if given by dns) at init(your begin() or similar method called from setup() after WiFi is up) and use that IP in subsequent reconnects.

**Comment by eos1d3** [comment]
I suggest waiting for real fix and using IP for the time being. Caching IP cannot help if ddns is used.

**Comment by marvinroger** [comment]
Please try the latest ESPAsyncTCP!

**Comment by eos1d3** [comment]
Using Adafruit IO with hostname, and use `mqttClient.disconnect()` to force disconnection.

Reconnect just works! :)

**Comment by eos1d3** [comment]
Oh... got this:
```

** Disconnected from the broker **
Reconnecting to MQTT...

Exception (28):
epc1=0x402046cc epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffef0:  3ffea5d0 3ffea5b8 3ffea5bd 00000000  
3fffff00:  402260d0 00000000 3ffe8a70 00000000  
3fffff10:  3ffeea58 3fff0050 3ffefbe0 402238ec  
3fffff20:  3fff0054 3fff0050 04fa8acf 402239b2  
3fffff30:  3fff0054 3fff0050 04fa4e56 40105e3c  
3fffff40:  40104fee 04faa94f 60000600 40226279  
3fffff50:  40105e30 00000000 04faa94f 00000000  
3fffff60:  4021bd84 3ffee208 3ffee230 60000600  
3fffff70:  0feef2d4 3ffee230 3ffee208 4021bd91  
3fffff80:  4021bdd6 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee258 3fffdad0 3ffeeb38 402055b7  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<
bBÊsBrûÎ¦jòÿ


```

**Comment by marvinroger** [comment]
Can you decode the stack dump? https://github.com/me-no-dev/EspExceptionDecoder/blob/master/README.md

@me-no-dev not totally fine yet!

**Comment by eos1d3** [comment]
I want to test more. Now using disconnect with 15 seconds to see what will happen.

**Comment by me-no-dev** [comment]
Let's see the stack decoded. Cant go more async than this :)

**Comment by eos1d3** [comment]
I am currently getting problem with Adafruit IO. It is not your problem. I tried with PubSub MQTT client, it also has the same problem.

It is Adafruit IO sometimes won't let you connect.  Once you try to connect it, it will disconnect you immediately. Like this:

`
Connecting to Wi-Fi... OK
Connecting to MQTT...
** Disconnected from the broker **
Reconnecting to MQTT...
** Disconnected from the broker **
Reconnecting to MQTT...
** Disconnected from the broker **
Reconnecting to MQTT...
** Disconnected from the broker **
Reconnecting to MQTT...
** Disconnected from the broker **
Reconnecting to MQTT...
** Disconnected from the broker **
`

I found after you run a sketch with their Adafruit MQTT client library, Then the problem will be fixed for any non-Adafruit MQTT client libraries for a while. So it looks like their server is looking for some kind of signature.

Another woke around is to just ignore the errors and wait for a while, the problem will disappear. Any idea for this problem?

**Comment by eos1d3** [comment]
I reported the problem in PubSubClient, one said: "Adafruit has added their own connack codes, they have their own broker." I don't know what it is.
See: https://github.com/knolleary/pubsubclient/issues/181

I think it is better to test with Moquitto with a DDNS name. I will try tomorrow.
Time to sleep now ;)

**Comment by marvinroger** [comment]
I have no idea, the MQTT protocol is standardized, I don't see why Adafruit would change anything. Moreover it would not even work once if it was the case.

**Comment by marvinroger** [comment]
https://io.adafruit.com/blog/

Code 6 : Client has exceeded connection rate limit. Please try again later.

So yes, you've disconnected too many times in a too short time window.

**Comment by eos1d3** [comment]
I will change my router to forward the port to Mosquitto tomorrow so that I can use a hostname to test.

But currently I suspect it is the reentrance of onMqttConnect or onMqttDisconnect callbacks as I disconnect too fast in just 6 seconds.

**Comment by marvinroger** [comment]
Yes this is the reason! Adafruit IO broker is throttled.

**Comment by eos1d3** [comment]
Still using Adafruit IO to test, with 60 seconds disconnect interval. After running for while, I got this:

```
** Disconnected from the broker **
Reconnecting to MQTT...

Exception (28):
epc1=0x40204764 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffef0:  00000000 3fffdad0 3ffeeb38 00000030  
3fffff00:  402261d0 00000000 3ffe8a68 00000000  
3fffff10:  3ffeea58 3fff0050 3ffeff28 402239ec  
3fffff20:  3fff0054 3fff0050 16842732 40223ac2  
3fffff30:  00000000 1683f883 40207007 40105e3c  
3fffff40:  40104fee 168445b4 60000600 40226379  
3fffff50:  40105e30 00000000 168445b4 00000000  
3fffff60:  4021be84 3ffee208 3ffee230 60000600  
3fffff70:  480db416 3ffee230 3ffee208 4021be91  
3fffff80:  4021bed6 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee240 3fffdad0 3ffeeb38 402056b7  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  

```

And decode these got the followings:
```
Decoding 15 results
0x402261d0: tcpip_tcp_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 81
0x402239ec: dns_check_entry at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 680
0x40223ac2: dns_tmr at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 313
0x40207007: pp_enable_noise_timer at ?? line ?
0x40105e3c: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 237
0x40104fee: wdt_feed at ?? line ?
0x40226379: sys_check_timeouts at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 420
0x40105e30: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 233
0x4021be84: ets_timer_handler_isr at ?? line ?
0x4021be91: ets_timer_handler_isr at ?? line ?
0x4021bed6: ets_timer_handler_isr at ?? line ?
0x402056b7: loop_task at C:\Users\andy\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp line 56

```

**Comment by eos1d3** [comment]
And this is another exception:

```
** Disconnected from the broker **
Reconnecting to MQTT...

Exception (28):
epc1=0x40204764 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffef0:  00000000 3fffdad0 3ffeeb38 00000030  
3fffff00:  402261d0 00000000 3ffe8a68 00000000  
3fffff10:  3ffeea58 3fff0050 3ffefcf8 402239ec  
3fffff20:  3fff0054 3fff0050 01839cfe 40223ab8  
3fffff30:  3fff0054 3fff0050 01837e7c 40105e3c  
3fffff40:  40104fee 0183bb80 60000600 40226379  
3fffff50:  40105e30 00000000 0183bb80 00000000  
3fffff60:  4021be84 3ffee208 3ffee230 60000600  
3fffff70:  04d8c6b1 3ffee230 3ffee208 4021be91  
3fffff80:  4021bed6 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee258 3fffdad0 3ffeeb38 402056b7  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

```

Decode messages:
```
Decoding 14 results
0x402261d0: tcpip_tcp_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 81
0x402239ec: dns_check_entry at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 680
0x40223ab8: dns_check_entries at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 727
:  (inlined by) dns_tmr at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 311
0x40105e3c: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 237
0x40104fee: wdt_feed at ?? line ?
0x40226379: sys_check_timeouts at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 420
0x40105e30: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 233
0x4021be84: ets_timer_handler_isr at ?? line ?
0x4021be91: ets_timer_handler_isr at ?? line ?
0x4021bed6: ets_timer_handler_isr at ?? line ?
0x402056b7: loop_task at C:\Users\andy\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp line 56

```

**Comment by me-no-dev** [comment]
can you please paste the epc1= line also next time? exception happens at 0x40204764 and the address is not decoded :)

**Comment by eos1d3** [comment]
How? Need more instruction to do. 

For all these address? 
epc1=0x40204764 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

**Comment by marvinroger** [comment]
Just paste the whole thing into the exception decoder, instead of only the content of the `>>>stack>>>` block.

**Comment by kiralikbeyin** [comment]
@me-no-dev 
I think you broke something when helping here...

```
Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(tm*)':
/Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp:67:64: error: 'strftime' was not declared in this scope
   strftime (result,30,"%a, %d %b %Y %H:%M:%S %Z", last_modified);
                                                                ^
/Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(time_t)':
/Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp:72:60: error: 'gmtime' was not declared in this scope
   return setLastModified((struct tm *)gmtime(&last_modified));
                                                            ^
/Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified()':
/Users/EvAkilli/Documents/Arduino/libraries/ESPAsyncWebServer-master/src/WebHandlers.cpp:77:25: error: 'time' was not declared in this scope
   if(time(&last_modified) == 0) //time is not yet set
```

**Comment by me-no-dev** [comment]
@kiralikbeyin use git version of esp8266 arduino and it will be fine

**Comment by eos1d3** [comment]
```
Exception (28):
epc1=0x40204764 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffef0:  3ffe9f8c 3ffe9f74 3ffe9f79 3ffe9f86  
3fffff00:  00000000 00000000 3ffe8a68 00000000  
3fffff10:  3ffeea58 3fff0050 3ffeff28 402239ec  
3fffff20:  3fff0054 3fff0050 12743e26 40223ac2  
3fffff30:  00000000 12740201 40207007 40105e3c  
3fffff40:  40104fee 12745ca6 60000600 40226379  
3fffff50:  40105e30 00000000 12745ca6 00000000  
3fffff60:  4021be84 3ffee208 3ffee230 60000600  
3fffff70:  3b0dfd88 3ffee230 3ffee208 4021be91  
3fffff80:  4021bed6 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee258 3fffdad0 3ffeeb38 402056b7  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<
```


```
Decoding 15 results
0x40204764: AsyncClient::_s_dns_found(char const*, ip_addr*, void*) at D:\Users\andy\Codes\Arduino\libraries\ESPAsyncTCP\src/ESPAsyncTCP.cpp line 506
0x402239ec: dns_check_entry at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 680
0x40223ac2: dns_tmr at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/dns.c line 313
0x40207007: pp_enable_noise_timer at ?? line ?
0x40105e3c: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 237
0x40104fee: wdt_feed at ?? line ?
0x40226379: sys_check_timeouts at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 420
0x40105e30: dns_timer at /Users/igrokhotkov/espressif/arduino/tools/sdk/lwip/src/core/timers.c line 233
0x4021be84: ets_timer_handler_isr at ?? line ?
0x4021be91: ets_timer_handler_isr at ?? line ?
0x4021bed6: ets_timer_handler_isr at ?? line ?
0x402056b7: loop_task at C:\Users\andy\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp line 56

```

**Comment by kiralikbeyin** [comment]
I said that 4 days ago it should be a DNS problem..

**Comment by me-no-dev** [comment]
@eos1d3 can you add a check [here](https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCP.cpp#L329) to see if maybe ipaddr is NULL?

**Comment by eos1d3** [comment]
@me-no-dev Wait! Why is my version different from the above?

```
void AsyncClient::_s_dns_found(const char *name, ip_addr_t *ipaddr, void *arg){
  AsyncClient* c = reinterpret_cast<AsyncClient*>(arg);
  IPAddress remote_addr;
  remote_addr = ipaddr->addr;
  c->connect(remote_addr, c->_connect_port);
}
```

And it starts on line 359.

**Comment by me-no-dev** [comment]
i pushed some commits since, but nothing important :)

**Comment by eos1d3** [comment]
Waiting for exception, it takes time.

**Comment by eos1d3** [comment]
I changed this for NULL checking.

```
void AsyncClient::_s_dns_found(const char *name, ip_addr_t *ipaddr, void *arg){
  AsyncClient* c = reinterpret_cast<AsyncClient*>(arg);
  IPAddress remote_addr;
  if (ipaddr == NULL)
	  Serial.println("------- ipaddr is NULL --------------");
  else
	  Serial.println("------- ipaddr is not NULL --------------");
  remote_addr = ipaddr->addr;
  c->connect(remote_addr, c->_connect_port);
}
```

It has been a while and I still cannot see any exception.
Is there any chance for timing issue? (Need to wait a while to get ipaddr?)

**Comment by me-no-dev** [comment]
can't be timing :) this function is called by lwip when there is result. Interesting though... I hope you get the same exception so we figure out what is going on.

**Comment by eos1d3** [comment]
It was easy to get exceptions before . But now I still can't get one.

**Comment by eos1d3** [comment]
Finally got it!

```
** Disconnected from the broker **
Reconnecting to MQTT...
**# ------- ipaddr is NULL --------------**

Exception (28):
epc1=0x4020477b epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffef0:  3ffeb438 00000000 3ffee9e4 4020477b  
3fffff00:  402261e8 00000000 3ffe8c50 00000000  
3fffff10:  3ffeec38 3fff0230 3ffefff0 40223a04  
3fffff20:  3fff0234 3fff0230 4e61563d 40223ad5  
3fffff30:  3fff0234 3fff0230 4e6137b8 40105e3c  
3fffff40:  40104fee 4e6174bd 60000600 40226391  
3fffff50:  40105e30 00000000 4e6174bd 00000000  
3fffff60:  4021be9c 3ffee3e8 3ffee410 60000600  
3fffff70:  fad17e6f 3ffee410 3ffee3e8 4021bea9  
3fffff80:  4021beee 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee420 3fffdad0 3ffeed18 402056cf  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

```

**Comment by me-no-dev** [comment]
what do you guys think is the best way to handle this case? call onDisconnect?

**Comment by eos1d3** [comment]
Pls explain to me the cause. onDisconnect is called twice to cause the problem?

**Comment by me-no-dev** [comment]
please pull the latest version of ESPAsyncTCP. It will call onError and onDisconnect in the case where DNS returns empty result (could not resolve the host).
It can happen for many reasons, but prolly the packet did not reach the DNS server or the ESP did not get the response.

**Comment by marvinroger** [comment]
I think `onDisconnect` is misused. It is called in case the connection failed (so you're not actually disconnected because you weren't actually connected). I would call this an error.

**Comment by me-no-dev** [comment]
many users might not attach to onError as it always leads to disconnect afterwards. I'm worried that they might miss the failure.

**Comment by marvinroger** [comment]
Makes sense. We can workaround this anyway, at the application level. ;)

Alright, let's wait for @eos1d3 feedback, so we can close both issues here and on ESPAsyncTCP!

**Comment by eos1d3** [comment]
Just tell me what you want me to do.
I still have time to test it.

**Comment by me-no-dev** [comment]
not get exception :)

**Comment by eos1d3** [comment]
@marvinroger Will you update your example so that we can confirm it works? And this saves time to test again for example.

**Comment by marvinroger** [comment]
There's nothing to chance, as @me-no-dev handled a DNS error the same way a normal failure would happen, so it would reconnect anyway. Nothing needs to change in the example :) just pull the latest ESPAsyncTCP git and check if there are no exceptions anymore.

**Comment by eos1d3** [comment]
OK. I will test it for at least one day. Will inform again if I find error.

BTW, is there any timeout setting in ESPAsyncTCP? And what is the default timeout?

**Comment by me-no-dev** [comment]
there is 5 seconds timeout between the time you send data and get an ACK from the other side. It's used to detect lost connection and calls onTimeout

**Comment by eos1d3** [comment]
When proxy or VPN is used, using 5 seconds may not be safe enough. And in some countries, like China, the internet is very slow to reach outside from China. I suggest giving an option for custom timeout setting.

**Comment by me-no-dev** [comment]
maybe look at the header? https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCP.h#L131

**Comment by me-no-dev** [comment]
ah nevermind... i see that I use the defined value here: https://github.com/me-no-dev/ESPAsyncTCP/blob/master/src/ESPAsyncTCP.cpp#L309

**Comment by me-no-dev** [comment]
done: https://github.com/me-no-dev/ESPAsyncTCP/commit/5987225cf66930b307a58f3ede3ba08830ee1c7b

**Comment by eos1d3** [comment]
It has been running for 15 hrs without any error with disconnection of 60 seconds intervals. This issue can be closed.

Great work! Thanks!

@me-no-dev Is `ASYNC_MAX_ACK_TIME` applied to both RX and TX operations?

**Comment by marvinroger** [comment]
Awesome, kudos @me-no-dev :)

**Comment by me-no-dev** [comment]
@eos1d3 you wait for ack only when you are sending a packet. RxTimeout deals with time since last incoming transmission (in cases where you want to close a connection if nothing has been received for some time)

**Comment by rmjjanssen1** [comment]
Hi There,

Seem to have the same issue with my setup trying to connect to Adafruit IO. Connecting, disconnecting with error code 0 and 6. Can somebody summarise how to fix the issue? Do I need to apply fix to ESPAsyncTCP?

Thanks for helping out....

R
